
#ifndef BUFFER_CONFIG_H
#define BUFFER_CONFIG_H

#include <stdint.h>

constexpr uint16_t COMMAND_PAYLOAD_SECTION_SIZE = 255;
constexpr uint16_t FILE_READ_BUFFER_SIZE = 128;
constexpr uint16_t FILE_READ_BUFFER_OFFSET = 5 + COMMAND_PAYLOAD_SECTION_SIZE;
constexpr uint16_t TOTAL_PACKET_BUFFER_SIZE = 5 + COMMAND_PAYLOAD_SECTION_SIZE + FILE_READ_BUFFER_SIZE;

#endif
